image: node:14.15-stretch
variables:
    FF_USE_FASTZIP: "true"
    OUTPUT_PATH: "$CI_PROJECT_DIR/artifacts"

cache:
    untracked: true
    policy: push
    key: ${CI_COMMIT_SHORT_SHA}
    paths:
        - node_modules/

.pull_cached_node_modules:
    cache:
        untracked: true
        key: ${CI_COMMIT_SHORT_SHA}
        policy: pull

stages:
    - setup
    - test

install:
    stage: setup
    script:
        - npm install

test:
    stage: test
    extends: .pull_cached_node_modules
    before_script:
        - apt-get update
        - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        - apt install -y ./google-chrome*.deb;
        - export CHROME_BIN=/usr/bin/google-chrome
    script:
        - npm run test t23-skellington -- --no-watch --no-progress --browsers=ChromeHeadlessCI --code-coverage
    coverage: '/Lines \W+: (\d+\.\d+)%.*/'
    artifacts:
        name: "tests-and-coverage"
        reports:
            junit:
                - $OUTPUT_PATH/tests/junit-test-results.xml

